import Link from "next/link";
import "./globals.css";

export const metadata = {
  title: "portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="bg-gradient-to-r  from-gray-500 via-violet-500 to-gray-500

"
      >
        <div className=" flex justify-center">
          <nav className="flex justify-between  w-3/4 rounded-lg bg-blue-950">
            <Link href={"/"}>
              <div className="text-white p-4  font-mono">Home</div>
            </Link>
            <Link href={"Educations"}>
              <div className="text-white p-4 font-mono">Eduction</div>
            </Link>
            <Link href={"Experience"}>
              <div className="text-white p-4 font-mono">Experience</div>
            </Link>
            <Link href={"Projects"}>
              <div className="text-white p-4 font-mono">Projects</div>
            </Link>
            <Link href={"ContactMe"}>
              <div className="text-white p-4 font-mono">Contact Me</div>
            </Link>
          </nav>
        </div>
        <div>{children}</div>
      </body>
    </html>
  );
}
